version: '3'
services:
  app:
    image: portafolio
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portafolio-container
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
